version: '3'
services:
  test_db:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: app_test
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app_test
    ports:
      - "54322:5432"

volumes:
  postgres: